export const SET_COFFEE_OBJ = 'SET_COFFEE_OBJ';
export const SET_SELECTED_COFFEE_TYPE = 'SET_SELECTED_COFFEE_TYPE';
export const SET_SELECTED_COFFEE_SIZE = 'SET_SELECTED_COFFEE_SIZE';
export const SET_SELECTED_COFFEE_SUBSELECTIONS = 'SET_SELECTED_COFFEE_SUBSELECTIONS';
export const SET_EMPLOYEE_ID = 'SET_EMPLOYEE_ID';
